/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ximalaya_mediamsssmpr_MediaNS */

#ifndef _Included_com_ximalaya_mediamsssmpr_MediaNS
#define _Included_com_ximalaya_mediamsssmpr_MediaNS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ximalaya_mediamsssmpr_MediaNS
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ximalaya_mediamsssmpr_MediaNS_init
  (JNIEnv *, jobject);

/*
 * Class:     com_ximalaya_mediamsssmpr_MediaNS
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ximalaya_mediamsssmpr_MediaNS_release
  (JNIEnv *, jobject);

/*
 * Class:     com_ximalaya_mediamsssmpr_MediaNS
 * Method:    ns
 * Signature: ([BI[BS)I
 */
JNIEXPORT jint JNICALL Java_com_ximalaya_mediamsssmpr_MediaNS_ns
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jshort);

/*
 * Class:     com_ximalaya_mediamsssmpr_MediaNS
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ximalaya_mediamsssmpr_MediaNS_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
